version: '3.6'

services:
  nestjs-rabbitmq:
    container_name: nestjs-rabbitmq
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      
    volumes:
      - ./mysql:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./init.sh:/docker-entrypoint-initdb.d/init.sh
    ports:
      - "3306:3306"
    command: ["/bin/bash", "/docker-entrypoint-initdb.d/init.sh"]


  