version: '3.6'

services:
  nestjs-rabbitmq:
    container_name: nestjs-rabbitmq
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_crud
      MYSQL_USER: user_crud
      MYSQL_PASSWORD: root
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "3307:3306"
  
  mysql2:
    image: mysql:8.0
    container_name: mysql_db2
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_crud2
      MYSQL_USER: user2_crud
      MYSQL_PASSWORD: root
    volumes:
      - ./mysql:/var/lib/mysql2
    ports:
      - "3308:3306"
